name: sharile
description: SHARiLE - File Sharing Solution


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  mime: ^0.9.7
  path_provider: ^1.6.21
  qr_flutter: ^3.2.0
  http_server: ^0.9.8+3
  file_picker: ^2.1.6
  get_ip: ^0.4.0
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
  - family: ShareTechMono
    fonts:
    - asset: fonts/ShareTechMono-Regular.ttf

